Update sync-fork.yaml
More attempts

diff --git a/.github/workflows/sync-fork.yaml b/.github/workflows/sync-fork.yaml
--- a/.github/workflows/sync-fork.yaml
+++ b/.github/workflows/sync-fork.yaml
@@ -12,7 +12,17 @@ jobs:
       - uses: actions/checkout@v4
       - name: Merge upstream
         run: |
-          git rebase `git merge-base core HEAD`
+          UPSTREAM=${{ inputs.upstream }};
+          if [ -z $UPSTREAM ]; then
+            echo ${{ github.token }} | gh auth login --with-token;
+            UPSTREAM=$(gh api repos/:owner/:repo --jq .parent.full_name);
+            if [ -z $UPSTREAM ]; then echo "Can't find upstream" >&2 && exit 1; fi;
+          fi;
+          if [ ! $(echo $UPSTREAM | egrep '^(http|git@)') ]; then
+            UPSTREAM=https://github.com/$UPSTREAM.git
+          fi;
+          git remote add upstream $UPSTREAM;
+          git rebase `git merge-base upstream HEAD`
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git push --force-with-lease origin core
